### PR TITLE
Issue #54 - Removed SplitButton and ToggleSplitButton

### PR DESCRIPTION
**Pull request by DamianSuess**
Addresses Issue #54

Removed documentation for the unimplemented `SplitButton` and `ToggleSplitButton` controls in Avalonia v0.10.x

### CODE REVIEW

**Comment by DamianSuess** [comment]
Hi folks, other than removing the files the 0.10.x, what else is needed to fulfill the needs of Issue #54?

**Comment by robloo** [comment]
I would also do a quick comparison to make sure the 0.10.x docs are identical to the 0.11.x docs for these controls. That ensures we aren't accidentally deleting some text.

**Comment by DamianSuess** [comment]
Thanks @robloo for the double check, comment. I'll skim over that when I get a chance and give a thumbs-up when finished.

**Comment by DamianSuess** [comment]
From what I can see, the documentation content between v0.10.x and v11.x are equivalent, except for the image samples are centered in v0.10.x. 

I also removed the reference from the `i18n\zh-Hans\` v0.10.x translation pages.

Should be good to go 👍

**Comment by robloo** [comment]
Build is failing due to invalid redirects:

image

**Comment by maxkatz6** [comment]
I will fix broken redirects after the merge. Thank you!

**Review by maxkatz6 — APPROVED** [review]

**Comment by DamianSuess** [comment]
Thank you @robloo & @maxkatz6, sorry i missed that, and thank you for taking care of it.

**Pull request merged**
