### PR TITLE
Bind to a Control with casting of parents DataContext

### PR DESCRIPTION
**Pull request by CodeDevAM**
Adds explanation how to cast the DataContext of a parents Control to access custom properties.

### CODE REVIEW

**Review by stevemonaco — COMMENTED** [review]
Some typos: parents -> parent's. it's -> its. an compile time error -> a compile-time error.

**Review by stevemonaco — CHANGES_REQUESTED** [review]
Sorry, I missed one thing. You should use "```xml" instead of markup. Looks good otherwise.

**Comment by CodeDevAM** [comment]
> Sorry, I missed one thing. You should use "```xml" instead of markup. Looks good otherwise.

But the rest of the file is also using "```markup" for XAML examples. Should the other occurances altered as well?

**Comment by stevemonaco** [comment]
> But the rest of the file is also using "```markup" for XAML examples. Should the other occurances altered as well?

After checking, it seems there's autodetection leads to the same highlighting anyways, so I guess it doesn't matter. Maintainers need to do a global pass of fixups in a separate issue.

**Review by stevemonaco — APPROVED** [review]

**Pull request merged**
