### PR TITLE
Update textbox.md to include `revealPasswordButton` style class

### PR DESCRIPTION
**Pull request by DamianSuess**
This PR provides documentation and sample code for using the `revealPasswordButton` style class on the TextBox user control.

### CODE REVIEW

**Comment by maxkatz6** [comment]
Thanks! The same change should be applied to the textbox.md file for 11.0 version. Also, this class might or might not be supported by third party themes, but is supported by fluent one.

**Comment by DamianSuess** [comment]
Appreciate the feedback as always @maxkatz6. Good callout on the Fluent theme. I'll make the updates and get it pushed up

**Comment by DamianSuess** [comment]
@maxkatz6, for the v11 docs, is that located in the path: `/avalonia-docs/docs/reference/controls/detailed-reference/textbox.md`

**Review by maxkatz6 — APPROVED** [review]
Thanks!

**Comment by maxkatz6** [comment]
@DamianSuess oh, haven't noticed your last comment. Yes, that's right, the second textbox file is located there.

**Pull request merged**
