### PR TITLE
zh-CN translate: developer-tools.md

### PR DESCRIPTION
**Pull request by LoongArum**

### CODE REVIEW

**Comment by rabbitism** [comment]
there was one, but i was busy so i didnt get chance to review https://github.com/AvaloniaUI/avalonia-docs/pull/503

**Comment by LoongArum** [comment]
> there was one, but i was busy so i didnt get chance to review #503

感谢兔基大佬的回复，我会尝试将 #503 该和并请求与我的工作合并，以减少你的工作负担，接下来我会尝试翻译更多未翻译的内容，还请多多指教！

**Comment by Iluvenis** [comment]
Merged in #503
已经合并了 #503

**Comment by LoongArum** [comment]
> Merged in #503 已经合并了 #503

好的，那我这个pull request 就关闭了！

**Comment by LoongArum** [comment]
> Merged in #503 已经合并了 #503

对了我现在在翻译常用的组件部分（内置控件里面的）我们不要又重复翻译了hh

**Pull request closed without merging**
