### PR TITLE
Simplified Chinese support

### PR DESCRIPTION
**Pull request by zdpcdt**
The avaloniachina community has translated the 11.0.0 documentation into Simplified Chinese, except for the `reference` - `Built-in controls` section.

### CODE REVIEW

**Comment by rabbitism** [comment]
Do we have any concerns on this PR?

**Comment by jmacato** [comment]
@rabbitism we've tested it and it doesnt seem to work

**Comment by rabbitism** [comment]
@jmacato Hi, how are you testing? if you are testing locally, you can only test for each locale individually. 
```bash
npm run start -- --locale zh-Hans
```
We have deployed this via GitHub Pages, please check 
https://avaloniachina.github.io/avalonia-docs/

The only concern from me is the hosting of static images. I don't know how it is going to be hosted on your server. Please refer to this 
https://docusaurus.io/zh-CN/docs/i18n/tutorial#deploy-your-site

**Comment by jmacato** [comment]
@rabbitism 
```
> avalonia-docs@0.0.0 start
> docusaurus start "--locale" "zh-Hans"

file:///var/home/strix/RiderProjects/avcina/node_modules/@docusaurus/core/bin/docusaurus.mjs:30
process.env.BABEL_ENV ??= 'development';
                       ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

```

**Comment by jmacato** [comment]
@rabbitism 

```
> avalonia-docs@0.0.0 start
> docusaurus start "--locale" "zh-Hans"

file:///  project dir  /node_modules/@docusaurus/core/bin/docusaurus.mjs:30
process.env.BABEL_ENV ??= 'development';
                       ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

```

**Comment by rabbitism** [comment]
I didn't see any env issue from my side 
image

**Comment by rabbitism** [comment]
Or maybe you can have another PR and commit to setup a basic structure with empty folder so we can move over the translated docs.

**Comment by MikeCodesDotNET** [comment]
YOLO

**Pull request merged**
