### PR TITLE
Update jetbrains-rider-setup.md - Added missing step to add plugin re…

### PR DESCRIPTION
**Pull request by mladenb**
…po in Rider

### CODE REVIEW

**Comment by maxkatz6** [comment]
I am pretty sure this plugin was supposed to be discoverable even without a special feed.
cc @ForNeVeR

**Comment by ForNeVeR** [comment]
@maxkatz6 is correct, you are not supposed to enter any additional URLs.

The instruction here is to get a "Dev" build of the plugin (which aren't intended for the general public, since I release new bug fixes and features pretty quick anyway after their merge to `main`).

A normal, "stable" version of the plugin is supposed to be available without adding of any URLs.

**Comment by mladenb** [comment]
I couldn't find this plugin in my Rider until after I added that url.

**Comment by ForNeVeR** [comment]
Please add some details. What version of Rider do you use?

Here's a support matrix for the stable plugin versions.
image

Pretty much every modern Rider version should be able to download the plugin (though the latest 1.2.0 with support for Rider 233 was only released recently).

**Comment by mladenb** [comment]
Hi, yeah, that could be the culprit. Here is my Rider version:
```
JetBrains Rider 2021.2.3
Build #RD-212.5712.52, built on December 23, 2021
```

**Comment by ForNeVeR** [comment]
That's a very old one, and probably I never released a stable version of the plugin for it (but there were some earlier dev versions compatible: that's why you can use them now).

There are no plans to support older versions of Rider. But feel free to use the older dev builds that are available in the said channel; I have no plans on removing these versions either.

My opinion is that it's not worth adding to the documentation.

**Comment by maxkatz6** [comment]
Closing in favor of #217 
Thank you @mladenb !

**Pull request closed without merging**
